apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: customer-service
  name: customer-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: customer-service
      version: v1
  template:
    metadata:
      labels:
        app: customer-service
        version: v1
    spec:
      containers:
      - image: evenh/customer-service:latest
        name: customer-service
        env:
        - name: ConnectionStrings__default
          valueFrom:
            secretKeyRef:
              name: customer-secret
              key: connectionString
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.4"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 3