# It is not recommended to run databases in containers
# 
# In this case, it's used for demonstration purposes only (with no persistence)

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: mongodb
  name: mongodb
  namespace: default
spec:
  selector:
    matchLabels:
      app: mongodb
      role: database
  template:
    metadata:
      labels:
        app: mongodb
        role: database
    spec:
      containers:
      - image: mongo:3-jessie
        name: mongodb
        ports:
        - name: mongodb
          containerPort: 27017

        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
        livenessProbe:
          tcpSocket:
            port: mongodb
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: mongodb
          initialDelaySeconds: 5
          periodSeconds: 10

---

kind: Service
apiVersion: v1
metadata:
  name: mongodb
  namespace: default
spec:
  selector:
    app: mongodb
  ports:
    - name: mongodb
      port: 27017
  type: ClusterIP